services:
  nextjs-frontend-main:
    build:
      context: ./frontend/nextjs-frontend-main
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    command: npm start
